services:
  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - /tmp/test-db:/var/lib/postgresql/data

  api:
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/src
    command: npx ts-node-dev --respawn src/server.ts
